name: Checking models on huggingface
on:
  # push:
    # branches:
      # - main
  # schedule:
    # - cron: 0 20 * * *
  workflow_dispatch:

env:
  PROCESS_COUNT: 8
  DOWNLOAD_ROOT: "https://raw.githubusercontent.com/go-skynet/model-gallery/main/prompt-templates/"
jobs:
  automatic-updates:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
        # with:
        #   ref: feat-experimental-python-hf-scraper
      # - uses: actions/setup-go@v4
      #   with:
      #     go-version: '>=1.21.0'
      - name: Check updates 🔧
        run: |
          # For now, still launch the golang scraper with this config
          # cd gallery-scrapers/go_huggingface
          # go get github.com/go-skynet/LocalAI@master
          # go mod tidy
          # go run ./main.go

          # Launch the new one
          pwd
          ls
          cd gallery-scrapers/huggingface
          . venv/Scripts/activate
          python main.py --count $PROCESS_COUNT --downloadRoot $DOWNLOAD_ROOT

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
